[package]
name = "vector_ops"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "vector_ops1"
path = "vector_ops1.rs"

[[bin]]
name = "vector_ops2"
path = "vector_ops2.rs"

[[bin]]
name = "vector_ops3"
path = "vector_ops3.rs"